Feature/ci add html validation (#11)
* add html5 validation within the CI
* use the experimental html validation
* remove css validation
* add a validation step
* limit the CI launch when html and css file have been updated

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,11 +3,11 @@ name: CI
 
 # Controls when the action will run.
 on:
-  # Triggers the workflow on push or pull request events but only for the master branch
-  # push:
-  #   branches: [ master ]
-  # pull_request:
-  #   branches: [ master ]
+  # Triggers the workflow on push events but only for specific files and path
+  push:
+    paths:
+    - '**.html'
+    - '**.css'
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -24,12 +24,27 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
+      # Runs html validation from "https://github.com/svenkreiss/html5validator"
+      - name: Html5 Validatior
+        id: validate
+        uses: Cyb3r-Jak3/html5validator-action-experimental@v1
+        with:
+          root: src/
+          format: xml
+          log_level: DEBUG
+          css: true
+
+      - name: Check outputs
+        run: |
+          if [[ "$VALID_OUT" -ne 0 ]]; then
+            echo "Validation step failed"
+            exit 1
+          fi
+        env:
+          VALID_OUT: ${{ steps.validate.outputs.result }}
 
       # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+      - uses: actions/upload-artifact@v2
+        with:
+          name: log
+          path: log.log
